spring.application.name=iot_manager_service

# --- CONEXION A POSTGRESQL ---
spring.datasource.url=jdbc:postgresql://postgres:5432/iot_manager_db
spring.datasource.username=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.profiles.include=secrets

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true


# --- PERFORMANCE Y CONCURRENCIA ---
spring.threads.virtual.enabled=true
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=20000

# Puertos del Servidor
# Puerto para el Frontend (REST)
server.port=8080
# Puerto exclusivo para el Router (gRPC)
grpc.server.port=-1
grpc.client.router-client.address=static://router:50052
grpc.client.router-client.negotiation-type=plaintext

spring.config.import=optional:file:application-secrets.properties


server.tomcat.threads.max=10
server.tomcat.max-connections=100


logging.level.root=INFO

logging.level.org.springframework.security=INFO
logging.level.org.springframework.web=INFO
logging.level.org.apache.catalina=WARN

logging.level.org.hibernate.SQL=WARN
logging.level.org.hibernate.orm.jdbc.bind=WARN

logging.level.com.iot.managerservice=INFO