spring.application.name=iot_manager_service

# --- CONEXION A POSTGRESQL ---
spring.datasource.url=jdbc:postgresql://localhost:5432/iot_manager_db
spring.datasource.username=tu_usuario
spring.datasource.password=tu_password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
# "update" crea o actualiza las tablas basandose en tus clases Java automaticamente (ideal para dev).
# En produccion, esto deberia ser "validate" o "none".
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false


# --- SUPABASE CONFIG ---
supabase.url=https://tu-proyecto.supabase.co
supabase.key=tu_anon_key_o_service_role_key


# --- PERFORMANCE Y CONCURRENCIA ---
spring.threads.virtual.enabled=true
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=20000

# Puertos del Servidor
# Puerto para el Frontend (REST)
server.port=8080
# Puerto exclusivo para el Edge/Router (gRPC)
grpc.server.port=9090